### ISSUE TITLE
[UI] Show short field label in the expression instead of full path

### ISSUE THREAD

**Issue by igarashitm** [atlasmap/atlasmap#868]
A full field path is always too long, it's like `MySourceDocumentID:/SourceOrder/Address/streetAddress1`. We should show a short label in the formula instead.

Also note that in Syndesis, Document ID is always a cryptic string Step ID and it's not visible to the user.

Now the field reference in expression uses field index like `${0}`, we must hide this from UI. This label thing is mandatory from beginning.

### TODO list
- [x] Add label - #917
- [x] Restore a cursor
- [ ] Restore highlighting text selection
- [x] Show field name instead of $[n} ref - #922
- [x] Show field full path as a tooltip - #922
- [x] Support removing field ref entirely with single [backspace] instead of removing just closing bracket

**Comment by igarashitm** [comment]
PatternFly Labels seems to be a way to go but there's no example. Need some technique to show in the textarea.
https://www.patternfly.org/pattern-library/forms-and-controls/labels/

**Comment by igarashitm** [comment]
Only this one satisfies our requirement it seems, embed tags in the input plain text
https://github.com/yairEO/tagify

**Comment by igarashitm** [comment]
#927 implemented basic concept. We'll follow up with other issues.
